### ISSUE TITLE
Memory Limit Exceeded using same concept

### ISSUE THREAD

**Issue by harshraj22** [MathProgrammer/Hacker-Earth#1]
Hi, I used the same concept as you described for [this question](https://www.hackerearth.com/practice/data-structures/advanced-data-structures/trie-keyword-tree/practice-problems/algorithm/xor-and-insert-92b9b529/description/). I just used map implementation of trie and I ain't able to pass more than 1 test case. Can you please help me out ?? My code :  

```
#include<bits/stdc++.h>
using namespace std;

struct trie{
	// bool end=false;
	int num=0;
	map<int,trie* > lk;

};
trie* root=nullptr;

trie* get(){
	trie* temp =new trie;
	temp->num=0;
	return temp;
}

void add(int n){
	if(root==nullptr)root=get();
	trie* node=root;
	for(int i=32;i>=0;i--){
		int val=(n & 1LL<<i)?1:0;
		if(node->lk.find(val)==node->lk.end())
			node->lk[val]=get();
		node=node->lk[val];
	}
	node->num=n;
}

int search(int n){
	if(root==nullptr || n==0)return 0;
	trie* node=root;
	for(int i=32;i>=0;i--){
		int val=(n & 1LL<<i)?1:0;
		if(node->lk.find(val)==node->lk.end())
			node=node->lk[1-val];
		else node=node->lk[val];
	}
	return node->num;
}

int main(){
	ios_base::sync_with_stdio(false);
	cin.tie(0);	cout.tie(0);
	int i,j,k,n,m=0;
	cin>>n;
	while(n--){
		cin>>j;
		if(j==3)cout<<(m^search(m))<<"\n";
		else cin>>k;

		if(j==1)add(k^m);
		else if(j==2)m^=k;
	}

	return 0;
}
```

**Comment by MathProgrammer** [comment]
Hi, 

I'm not sure about this implementation of trie. Maybe it took too much memory.

**Comment by harshraj22** [comment]
> Hi,
> 
> I'm not sure about this implementation of trie. Maybe it took too much memory.

Can you please try it once ? On my machine, I tried with the outputs that gave memory limit verdict, but it worked smoothly here.
